/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LayoutHomeRouteImport } from './routes/_layout.home'
import { Route as LayoutAnalyticsRouteImport } from './routes/_layout.analytics'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as LayoutpostPostsRouteImport } from './routes/_layout/(post)/posts'
import { Route as LayoutpostPostsPostIdRouteImport } from './routes/_layout/(post)/posts.$postId'
import { Route as LayoutpostPostsPostIdCommentsRouteImport } from './routes/_layout/(post)/posts.$postId.comments'
import { Route as LayoutpostPostsPostIdCommentsCommentIdRouteImport } from './routes/_layout/(post)/posts.$postId.comments.$commentId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutHomeRoute = LayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsRoute = LayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const LayoutpostPostsRoute = LayoutpostPostsRouteImport.update({
  id: '/(post)/posts',
  path: '/posts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutpostPostsPostIdRoute = LayoutpostPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => LayoutpostPostsRoute,
} as any)
const LayoutpostPostsPostIdCommentsRoute =
  LayoutpostPostsPostIdCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => LayoutpostPostsPostIdRoute,
  } as any)
const LayoutpostPostsPostIdCommentsCommentIdRoute =
  LayoutpostPostsPostIdCommentsCommentIdRouteImport.update({
    id: '/$commentId',
    path: '/$commentId',
    getParentRoute: () => LayoutpostPostsPostIdCommentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutRouteWithChildren
  '/analytics': typeof LayoutAnalyticsRoute
  '/home': typeof LayoutHomeRoute
  '/posts': typeof LayoutpostPostsRouteWithChildren
  '/admin/': typeof AdminAdminIndexRoute
  '/posts/$postId': typeof LayoutpostPostsPostIdRouteWithChildren
  '/posts/$postId/comments': typeof LayoutpostPostsPostIdCommentsRouteWithChildren
  '/posts/$postId/comments/$commentId': typeof LayoutpostPostsPostIdCommentsCommentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutRouteWithChildren
  '/analytics': typeof LayoutAnalyticsRoute
  '/home': typeof LayoutHomeRoute
  '/posts': typeof LayoutpostPostsRouteWithChildren
  '/admin': typeof AdminAdminIndexRoute
  '/posts/$postId': typeof LayoutpostPostsPostIdRouteWithChildren
  '/posts/$postId/comments': typeof LayoutpostPostsPostIdCommentsRouteWithChildren
  '/posts/$postId/comments/$commentId': typeof LayoutpostPostsPostIdCommentsCommentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/analytics': typeof LayoutAnalyticsRoute
  '/_layout/home': typeof LayoutHomeRoute
  '/_layout/(post)/posts': typeof LayoutpostPostsRouteWithChildren
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_layout/(post)/posts/$postId': typeof LayoutpostPostsPostIdRouteWithChildren
  '/_layout/(post)/posts/$postId/comments': typeof LayoutpostPostsPostIdCommentsRouteWithChildren
  '/_layout/(post)/posts/$postId/comments/$commentId': typeof LayoutpostPostsPostIdCommentsCommentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/home'
    | '/posts'
    | '/admin/'
    | '/posts/$postId'
    | '/posts/$postId/comments'
    | '/posts/$postId/comments/$commentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/home'
    | '/posts'
    | '/admin'
    | '/posts/$postId'
    | '/posts/$postId/comments'
    | '/posts/$postId/comments/$commentId'
  id:
    | '__root__'
    | '/_admin'
    | '/_layout'
    | '/_layout/analytics'
    | '/_layout/home'
    | '/_layout/(post)/posts'
    | '/_admin/admin/'
    | '/_layout/(post)/posts/$postId'
    | '/_layout/(post)/posts/$postId/comments'
    | '/_layout/(post)/posts/$postId/comments/$commentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/home': {
      id: '/_layout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics': {
      id: '/_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_layout/(post)/posts': {
      id: '/_layout/(post)/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof LayoutpostPostsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/(post)/posts/$postId': {
      id: '/_layout/(post)/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof LayoutpostPostsPostIdRouteImport
      parentRoute: typeof LayoutpostPostsRoute
    }
    '/_layout/(post)/posts/$postId/comments': {
      id: '/_layout/(post)/posts/$postId/comments'
      path: '/comments'
      fullPath: '/posts/$postId/comments'
      preLoaderRoute: typeof LayoutpostPostsPostIdCommentsRouteImport
      parentRoute: typeof LayoutpostPostsPostIdRoute
    }
    '/_layout/(post)/posts/$postId/comments/$commentId': {
      id: '/_layout/(post)/posts/$postId/comments/$commentId'
      path: '/$commentId'
      fullPath: '/posts/$postId/comments/$commentId'
      preLoaderRoute: typeof LayoutpostPostsPostIdCommentsCommentIdRouteImport
      parentRoute: typeof LayoutpostPostsPostIdCommentsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LayoutpostPostsPostIdCommentsRouteChildren {
  LayoutpostPostsPostIdCommentsCommentIdRoute: typeof LayoutpostPostsPostIdCommentsCommentIdRoute
}

const LayoutpostPostsPostIdCommentsRouteChildren: LayoutpostPostsPostIdCommentsRouteChildren =
  {
    LayoutpostPostsPostIdCommentsCommentIdRoute:
      LayoutpostPostsPostIdCommentsCommentIdRoute,
  }

const LayoutpostPostsPostIdCommentsRouteWithChildren =
  LayoutpostPostsPostIdCommentsRoute._addFileChildren(
    LayoutpostPostsPostIdCommentsRouteChildren,
  )

interface LayoutpostPostsPostIdRouteChildren {
  LayoutpostPostsPostIdCommentsRoute: typeof LayoutpostPostsPostIdCommentsRouteWithChildren
}

const LayoutpostPostsPostIdRouteChildren: LayoutpostPostsPostIdRouteChildren = {
  LayoutpostPostsPostIdCommentsRoute:
    LayoutpostPostsPostIdCommentsRouteWithChildren,
}

const LayoutpostPostsPostIdRouteWithChildren =
  LayoutpostPostsPostIdRoute._addFileChildren(
    LayoutpostPostsPostIdRouteChildren,
  )

interface LayoutpostPostsRouteChildren {
  LayoutpostPostsPostIdRoute: typeof LayoutpostPostsPostIdRouteWithChildren
}

const LayoutpostPostsRouteChildren: LayoutpostPostsRouteChildren = {
  LayoutpostPostsPostIdRoute: LayoutpostPostsPostIdRouteWithChildren,
}

const LayoutpostPostsRouteWithChildren = LayoutpostPostsRoute._addFileChildren(
  LayoutpostPostsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAnalyticsRoute: typeof LayoutAnalyticsRoute
  LayoutHomeRoute: typeof LayoutHomeRoute
  LayoutpostPostsRoute: typeof LayoutpostPostsRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAnalyticsRoute: LayoutAnalyticsRoute,
  LayoutHomeRoute: LayoutHomeRoute,
  LayoutpostPostsRoute: LayoutpostPostsRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
